#!/usr/bin/env python3
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]

ICON_DIR = ROOT / "apps" / "bundled" / "filemgr" / "src" / "www" / "icons" / "filetypes"
WEB_OUT = ROOT / "apps" / "bundled" / "filemgr" / "src" / "www" / "filetype_icons.js"

ANDROID_PKG = "com.pqnas.mobile.files"
ANDROID_OUT = (
        ROOT
        / "app"
        / "src"
        / "main"
        / "java"
        / "com"
        / "pqnas"
        / "mobile"
        / "files"
        / "FileTypeIcons.kt"
)

ANDROID_ASSET_DIR = ROOT / "app" / "src" / "main" / "assets" / "filetypes"

# Physical SVG master icons stay small and traditional.
# Extensions below are aliases to those masters.
ALIAS_GROUPS = {
    "generic_archive": [
        "7z", "apk", "bz2", "deb", "dmg", "gz", "img", "iso", "msi",
        "rar", "rpm", "tar", "tgz", "xz", "zip"
    ],
    "generic_audio": [
        "aac", "flac", "m4a", "mp3", "ogg", "wav"
    ],
    "generic_video": [
        "avi", "m4v", "mkv", "mov", "mp4", "tsv", "webm"
    ],
    "generic_image": [
        "bmp", "gif", "heic", "ico", "jpeg", "jpg", "png", "svg", "tiff", "webp"
    ],
    "generic_spreadsheet": [
        "csv", "ods", "xls", "xlsx"
    ],
    "generic_presentation": [
        "key", "odp", "ppt", "pptx"
    ],
    "generic_pdf": [
        "pdf"
    ],
    "generic_text": [
        "log", "md", "txt"
    ],
    "generic_document": [
        "doc", "docx", "odt", "rtf"
    ],
    "generic_config": [
        "bak", "cfg", "conf", "crt", "ini", "lock", "pem", "tmp"
    ],
    "generic_database": [
        "db", "sqlite", "sql"
    ],
    "generic_font": [
        "otf", "ttf", "woff", "woff2"
    ],
    "generic_code": [
        "bash", "css", "cxx", "exe", "go",
        "hh", "hpp", "htm", "html", "hxx", "java", "js", "json",
        "jsx", "kt", "lua", "mjs", "php", "ps1", "py", "r", "rb",
        "rs", "scss", "sh", "so", "swift", "toml", "ts", "tsx",
        "xml", "yaml", "yml", "zsh"
    ],
}

FILETYPE_ICON_ALIASES = {
    ext: master
    for master, exts in ALIAS_GROUPS.items()
    for ext in exts
}


def kotlin_string_list(items: list[str]) -> str:
    if not items:
        return ""
    return ",\n".join(f'        "{x}"' for x in items)


def kotlin_map_entries(items: dict[str, str]) -> str:
    if not items:
        return ""
    return ",\n".join(
        f'        "{ext}" to "{master}"'
        for ext, master in sorted(items.items())
    )


def resolve_web_icons(master_icons: dict[str, str]) -> dict[str, str]:
    icons = dict(master_icons)

    for ext, master in sorted(FILETYPE_ICON_ALIASES.items()):
        if master not in master_icons:
            raise SystemExit(f"Alias {ext} points to missing master icon: {master}")
        icons[ext] = master_icons[master]

    return icons


def build_web_js(master_icons: dict[str, str]) -> str:
    icons = resolve_web_icons(master_icons)

    js = []
    js.append("// Auto-generated by tools/generate_filetype_icon_map.py")
    js.append("// Do not edit by hand.")
    js.append("(function(){")
    js.append('  "use strict";')
    js.append(
        f"  window.PQNAS_FILE_ICONS = {json.dumps(icons, ensure_ascii=False, separators=(',', ':'))};"
    )
    js.append("})();")
    js.append("")
    return "\n".join(js)


def build_android_kotlin(master_icon_names: list[str]) -> str:
    icon_names_sorted = sorted(master_icon_names)
    names_block = kotlin_string_list(icon_names_sorted)
    alias_block = kotlin_map_entries(FILETYPE_ICON_ALIASES)

    return f"""// Auto-generated by tools/generate_filetype_icon_map.py
// Do not edit by hand.

package {ANDROID_PKG}

import com.pqnas.mobile.api.FileItemDto
import java.util.Locale

object FileTypeIcons {{
    private const val ASSET_PREFIX = "file:///android_asset/filetypes/"

    const val DEFAULT_ICON = ASSET_PREFIX + "default.svg"
    const val FOLDER_ICON = ASSET_PREFIX + "folder.svg"

    private val KNOWN_ICONS = setOf(
{names_block}
    )

    private val EXTENSION_ICON_ALIASES = mapOf(
{alias_block}
    )

    fun iconFor(item: FileItemDto): String {{
        if (item.type == "dir") return FOLDER_ICON
        return iconForName(item.name)
    }}

    fun iconForName(name: String?): String {{
        if (name.isNullOrBlank()) return DEFAULT_ICON

        val trimmed = name.trim()
        val ext = trimmed.substringAfterLast('.', "").lowercase(Locale.ROOT)

        val mapped = EXTENSION_ICON_ALIASES[ext] ?: ext
        if (mapped.isNotBlank() && mapped in KNOWN_ICONS) {{
            return iconPath(mapped)
        }}

        return fallbackForExtension(ext)
    }}

    private fun fallbackForExtension(ext: String): String {{
        if (ext.isBlank()) return DEFAULT_ICON

        return when (ext) {{
            // archives
            "zip", "7z", "rar", "tar", "gz", "tgz", "bz2", "xz", "deb", "rpm", "dmg", "apk" ->
                iconPath(if ("generic_archive" in KNOWN_ICONS) "generic_archive" else "default")

            // audio
            "mp3", "wav", "ogg", "flac", "m4a", "aac" ->
                iconPath(if ("generic_audio" in KNOWN_ICONS) "generic_audio" else "default")

            // video
            "mp4", "m4v", "mov", "mkv", "avi", "webm", "tsv" ->
                iconPath(if ("generic_video" in KNOWN_ICONS) "generic_video" else "default")

            // images
            "png", "jpg", "jpeg", "gif", "bmp", "svg", "webp", "tiff", "ico", "heic" ->
                iconPath(if ("generic_image" in KNOWN_ICONS) "generic_image" else "default")

            // spreadsheets
            "xls", "xlsx", "csv", "ods" ->
                iconPath(if ("generic_spreadsheet" in KNOWN_ICONS) "generic_spreadsheet" else "default")

            // presentations
            "ppt", "pptx", "odp", "key" ->
                iconPath(if ("generic_presentation" in KNOWN_ICONS) "generic_presentation" else "default")

            // documents
            "doc", "docx", "pdf", "txt", "md", "rtf", "odt", "ini", "cfg", "conf", "log" ->
                iconPath(if ("generic_document" in KNOWN_ICONS) "generic_document" else "default")

            // databases
            "db", "sqlite", "sql" ->
                iconPath(if ("generic_database" in KNOWN_ICONS) "generic_database" else "default")

            // code / scripts
            "c", "cc", "cpp", "cxx", "h", "hh", "hpp", "hxx",
            "java", "kt", "ts", "tsx", "js", "jsx", "json",
            "html", "htm", "css", "scss", "php", "py", "rb",
            "rs", "go", "sh", "bash", "zsh", "lua", "swift",
            "xml", "yml", "yaml", "toml", "so", "dll", "exe" ->
                iconPath(if ("generic_code" in KNOWN_ICONS) "generic_code" else "default")

            else -> DEFAULT_ICON
        }}
    }}

    private fun iconPath(name: String): String {{
        return ASSET_PREFIX + name + ".svg"
    }}
}}
"""


def copy_android_assets(icon_files: list[Path]) -> int:
    ANDROID_ASSET_DIR.mkdir(parents=True, exist_ok=True)

    for old in ANDROID_ASSET_DIR.glob("*.svg"):
        old.unlink()

    count = 0
    for src in icon_files:
        dst = ANDROID_ASSET_DIR / src.name
        dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
        count += 1
    return count


def main() -> int:
    if not ICON_DIR.is_dir():
        raise SystemExit(f"Icon directory not found: {ICON_DIR}")

    icon_files = []
    master_icons = {}

    for p in sorted(ICON_DIR.glob("*.svg")):
        if not p.is_file():
            continue
        icon_files.append(p)
        master_icons[p.stem] = p.read_text(encoding="utf-8")

    required = [
        "default",
        "folder",
        "generic_archive",
        "generic_audio",
        "generic_code",
        "generic_database",
        "generic_document",
        "generic_file",
        "generic_image",
        "generic_presentation",
        "generic_spreadsheet",
        "generic_video",
    ]
    missing = [k for k in required if k not in master_icons]
    if missing:
        raise SystemExit(f"Missing required icons: {', '.join(missing)}")

    for ext, master in FILETYPE_ICON_ALIASES.items():
        if master not in master_icons:
            raise SystemExit(f"Alias {ext} points to missing master icon: {master}")

    WEB_OUT.parent.mkdir(parents=True, exist_ok=True)
    WEB_OUT.write_text(build_web_js(master_icons), encoding="utf-8")

    android_project_root = ROOT / "app" / "src" / "main"

    print(f"[OK] wrote {WEB_OUT} ({len(resolve_web_icons(master_icons))} web mappings, {len(master_icons)} master icons)")

    if android_project_root.is_dir():
        ANDROID_OUT.parent.mkdir(parents=True, exist_ok=True)
        ANDROID_OUT.write_text(
            build_android_kotlin(sorted(master_icons.keys())),
            encoding="utf-8"
        )

        copied = copy_android_assets(icon_files)
        print(f"[OK] wrote {ANDROID_OUT}")
        print(f"[OK] copied {copied} svg assets to {ANDROID_ASSET_DIR}")
    else:
        print("[SKIP] Android project not found; skipped Android icon outputs")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
